abbreviations = [["tjr", "toujours"],
                 ["tjrs", "toujours"],
                 ["ds", "dans"],
                 ["tkt", "ne t’inquiète pas"],
                 ["bjr", "bonjour"],
                 ["slt", "salut"],
                 ["slu", "salut"],
                 ["lu", "salut"],
                 ["lut", "salut"],
                 ["yop", "salut"],
                 ["bsr", "bonsoir"],
                 ["cad", "c'est-à-dire"],
                 ["càd", "c'est-à-dire"],
                 ["c.-à-d", "c'est-à-dire"],
                 ["c.a.d", "c'est-à-dire"],
                 ["dr", "docteur"],
                 ["doc", "docteur"],
                 ["dre", "docteure"],
                 ["doct", "docteur"],
                 ["ex", "exemple"],
                 ["exo", "exercice"],
                 ["exos", "exercices"],
                 ["exerc", "exercice"],
                 ["exp", "explication"],
                 ["géo", "géographie"],
                 ["maths", "mathématiques"],
                 ["math", "mathématiques"],
                 ["mr", "monsieur"],
                 ["mm", "messieurs"],
                 ["qqch", "quelquechose"],
                 ["ch", "chose"],
                 ["bcp", "beaucoup"],
                 ["c", "c'est"],
                 ["ct", "c'était"],
                 ["dsl", "désolé"],
                 ["g", "j'ai"],
                 ["ki", "qui"],
                 ["koi", "quoi"],
                 ["mdr", "mort-de-rire"],
                 ["msg", "message"],
                 ["mess", "message"],
                 ["sry", "désolé"],
                 ["t", "t'es"],
                 ["vrmt", "vraiment"],
                 ["we", "weekend"],
                 ["ya", "il y a"],
                 ["y'a", "il y a"],
                 ["bzr", "bizarre"],
                 ["chelou", "bizarre"],
                 ["ann", "annexe"],
                 ["ant", "antérieur"],
                 ["app", "appartement"],
                 ["appt", "appartement"],
                 ["apt", "appartement"],
                 ["arrt", "arrondissement"],
                 ["art", "article"],
                 ["auj", "aujourd’hui"],
                 ["ojd", "aujourd’hui"],
                 ["oj", "aujourd’hui"],
                 ["ajd", "aujourd’hui"],
                 ["alp", "à la prochaine"],
                 ["avc", "avec"],
                 ["ac", "avec"],
                 ["bac", "baccalauréat"],
                 ["bât", "bâtiment"],
                 ["bt", "bâtiment"],
                 ["bd", "boulevard"],
                 ["boul", "boulevard"],
                 ["cdmt", "cordialement"],
                 ["chauff", "chauffage"],
                 ["chap", "chapitre"],
                 ["contr", "contraire"],
                 ["cpdt", "cependant"],
                 ["cpd", "cependant"],
                 ["crs", "cours"],
                 ["dc", "donc"],
                 ["dir", "directeur"],
                 ["dpdv", "du-point-de-vue"],
                 ["dvt", "devant"],
                 ["€", "Euro"],
                 ["éd", "édition"],
                 ["env", "environ"],
                 ["&", "et"],
                 ["fact", "facture"],
                 ["févr", "févrie"],
                 ["fevr", "févrie"],
                 ["fig", "figure"],
                 ["fr", "français"],
                 ["franç", "français"],
                 ["fra", "france"],
                 ["gd", "grand"],
                 ["h", "heure"],
                 ["hab", "habitant"],
                 ["hs", "hors-service"],
                 ["ht", "hors-taxes"],
                 ["jf", "jeune-femme"],
                 ["jh", "jeune-homme"],
                 ["jms", "jamais"],
                 ["j o", "jeux-olympiques"],
                 ["jo", "journal-officiel"],
                 ["kg", "kilogramme"],
                 ["km", "kilomètre"],
                 ["loc", "location"],
                 ["m̂", "même"],
                 ["m", "même"],
                 ["mm", "même"],
                 ["min", "minute"],
                 ["mlle", "mademoiselle"],
                 ["mlles", "mesdemoiselles"],
                 ["mme", "madame"],
                 ["mmes", "mesdames"],
                 ["mtn", "maintenant"],
                 ["opt", "option"],
                 ["pb", "problème"],
                 ["pcq", "parce-que"],
                 ["psk", "parce-que"],
                 ["p.c.q", "parce-que"],
                 ["pck", "parce-que"],
                 ["pdt", "pendant"],
                 ["p.ex.", "par exemple"],
                 ["p ex", "par exemple"],
                 ["pq", "pourquoi"],
                 ["pk", "pourquoi"],
                 ["prk", "pourquoi"],
                 ["pkoi", "pourquoi"],
                 ["pl", "place"],
                 ["plrs", "plusieurs"],
                 ["pls", "plusieurs"],
                 ["pr", "pour"],
                 ["pt", "points"],
                 ["pts", "point"],
                 ["pti", "pour ton information"],
                 ["pub", "publicité"],
                 ["qcq", "quelconque"],
                 ["qd", "quand"],
                 ["qq", "quelque"],
                 ["qqf", "quelquefois"],
                 ["qqn", "quelqu’un"],
                 ["kk1", "quelqu’un"],
                 ["qqun", "quelqu'un"],
                 ["qq1", "quelqu'un"],
                 ["qqpt", "quelque-part"],
                 ["qdm", "quand-meme"],
                 ["RV", "rendez-vous"],
                 ["rdv", "rendez-vous"],
                 ["rsvp", "répondez s’il vous plaît"],
                 ["sec", "seconde"],
                 ["sect", "section"],
                 ["spec", "spécification"],
                 ["sté", "société"],
                 ["stp", "s’il te plaît"],
                 ["suiv", "suivant"],
                 ["suppl", "supplément"],
                 ["svp", "s’il vous plaît"],
                 ["tél", "téléphone"],
                 ["tjs", "toujours"],
                 ["tlm", "tout le monde"],
                 ["tq", "tel-que"],
                 ["ts", "tous"],
                 ["tt", "tout"],
                 ["vol", "volume"],
                 ["vs", "vous"],
                 ["absolt", "absolument"],
                 ["adm", "administration"],
                 ["admin", "administration"],
                 ["av", "avant"],
                 ["avt", "avant"],
                 ["expr", "expression"],
                 ["fut", "futur"],
                 ["hist", "histoire"],
                 ["bp", "beaucoup"],
                 ["bcq", "beaucoup"],
                 ["dd", "dedans"],
                 ["déf", "définition"],
                 ["etc", "et-cetera"],
                 ["ext", "extérieur"],
                 ["ft", "font"],
                 ["gd", "grand"],
                 ["gp", "groupe"],
                 ["intro", "introduction"],
                 ["jr", "jour"],
                 ["jrs", "jours"],
                 ["lt", "long-terme"],
                 ["lsq", "lorsque"],
                 ["ms", "mais"],
                 ["^m", "meme"],
                 ["mt", "moyen-terme"],
                 ["nb", "nombre"],
                 ["nbre", "nombre"],
                 ["nbx", "nombreux"],
                 ["obs", "observation"],
                 ["p", "page"],
                 ["pers", "personne"],
                 ["pê", "peut-être"],
                 ["prtt", "pourtant"],
                 ["qté", "quantité"],
                 ["qt", "quantité"],
                 ["q", "que"],
                 ["quest", "question"],
                 ["rv", "rendez-vous"],
                 ["resp", "responsabilité"],
                 # ["slt", "seulement"],
                 ["sol", "solution"],
                 ["st", "sont"],
                 ["svt", "souvent"],
                 ["tps", "temps"],
                 ["s/s", "sous"],
                 ["tte", "toute"],
                 ["agr", "agriculture"],
                 ["ap", "après"],
                 ["id", "comme"],
                 ["co", "comment"],
                 ["ccl", "conclusion"],
                 ["csq", "conséquence"],
                 ["dvlpt", "developpement"],
                 ["dt", "dont"],
                 ["eco", "Economie"],
                 ["ent", "entreprise"],
                 ["gvt", "gouvernement"],
                 ["gouv", "gouvernement"],
                 ["impt", "important "],
                 ["ind", "industrie"],
                 ["lg", "long"],
                 ["lgtps", "longtemps"],
                 ["mvt", "mouvement"],
                 ["ns", "nous"],
                 ["nv", "nouveau"],
                 ["pfs", "parfois"],
                 ["pol", "politique"],
                 ["pop", "population"],
                 ["bb", "bébé"],
                 ["pvoir", "Pouvoir"],
                 ["prod", "production"],
                 ["qqfois", "quelque-fois"],
                 ["ss", "sans"],
                 ["w", "travail"],
                 ["sligner", "souligner"],
                 ["sup", "supérieur"],
                 ["inf", "inférieur"],
                 ["max", "maximum"],
                 ["min", "minimum"],
                 ["tx", "taux"],
                 ["vloir", "vouloir"],
                 ["adr", "adresse"],
                 ["cie", "compagnie"],
                 ["no", "numéro"],
                 ["nos", "numéros"],
                 ["pj", "pièce-jointe"],
                 ["p.j", "pièce-jointe"],
                 ["téléc", "télécopie"],
                 ["anc", "ancien"],
                 ["angl", "anglais"],
                 ["esp", "espagnol"],
                 ["cap", "capital"],
                 ["dép", "département"],
                 ["étr", "étranger"],
                 ["fém", "féminin"],
                 ["gal", "général"],
                 ["gén", "général"],
                 ["h", "homme"],
                 ["mn", "minute"],
                 ["partic", "particulier"],
                 ["princ", "principal"],
                 ["qqs", "quelques"],
                 ["rq", "remarque"],
                 ["sg", "singulier"],
                 ["v", "vers"],
                 ["vx", "vieux"],
                 ["vb", "verbe"],
                 ["a+", "a plus"],
                 ["abs", "absent"],
                 ["ama", "à mon avis"],
                 ["att", "attend"],
                 ["bap", "bise aux petits"],
                 ["bg", "beau-gosse"],
                 ["biz" "bise"],
                 ["bz", "bise"],
                 ["bj", "bien-joué"],
                 ["bn", "bonne-nuit"],
                 ["b8", "bonne-nuit"],
                 ["bn8", "bonne-nuit"],
                 ["bsx", "bisoux"],
                 ["bvo", "bravo"],
                 ["c", "c'est"],
                 ["cc", "coucou"],
                 ["couc", "coucou"],
                 ["kikoo", "coucou"],
                 ["kikou", "coucou"],
                 ["chui", "je suis"],
                 ["cki", "c'est qui"],
                 ["cmb", "combien"],
                 ["cpg", "c'est pas grave"],
                 ["ctb", "c'était bien"],
                 ["ctup", "c'est toujours un plaisir"],
                 ["d100", "descends"],
                 ["dac", "d'accord"],
                 ["dacc", "d'accord"],
                 ["dak", "d'accord"],
                 ["dcdr", "décédé de rire"],
                 ["deco", "se déconnecter"],
                 ["reco", "se reconnecter"],
                 ["dr", "de rien"],
                 ["dr1", "de rien"],
                 ["dtf", "de toute façon"],
                 ["ect", "écoute"],
                 ["fpc", "fais pas chier"],
                 ["ftg", "ferme ta gueule"],
                 ["g", "j’ai"],
                 ["geta", "Google est ton ami"],
                 ["gf1", "j’ai faim"],
                 ["hihi", "rire"],
                 ["jam", "j'en ai marre"],
                 ["jtm", "je t'aime"],
                 ["jdç", "je dis ça"],
                 ["dr", "je ne dis rien"],
                 ["jevtd ", "je vais t’aider"],
                 ["jmef", "je m'en fous"],
                 ["jrb", "je ris beaucoup"],
                 ["jre", "je reviens"],
                 ["jta", "je t'adore"],
                 ["jtdr", "je t'adore"],
                 ["jtd", "je t'adore"],
                 ["jtbf", "je t'embrasse bien fort"],
                 ["jtl", "je te love"],
                 ["jtlg", "je te love grave"],
                 ["jtm", "je t'aime"],
                 ["kc", "cassé"],
                 ["kdo", "cadeau"],
                 ["kestuf", "qu'est ce que tu fais"],
                 ["klr", "clair"],
                 ["koi29", "quoi de neuf"],
                 ["koid9", "quoi de neuf"],
                 ["krs", "caresse"],
                 ["lgtmps", "longtemps"],
                 ["lgtmp", "longtemps"],
                 ["mdl", "mort de lol"],
                 ["mdp", "mot de passe"],
                 ["merki", "merci"],
                 ["mic", "merci"],
                 ["mci", "merci"],
                 ["ci", "merci"],
                 ["miki", "merci"],
                 ["mnt", "maintenant"],
                 ["mtnt", "maintenant"],
                 ["mouaha", "rire"],
                 ["mouhaha", "rire"],
                 ["mouai", "oui mais"],
                 ["mp", "message personnel"],
                 ["pv", "privé"],
                 ["mpm", "même pas mal"],
                 ["mrd", "merde"],
                 ["mwa", "moi"],
                 ["moa", "moi"],
                 ["moua", "moi"],
                 ["me", "moi"],
                 ["ndc", "nom de compte"],
                 ["nn", "non"],
                 ["nan", "non"],
                 ["na", "non"],
                 ["nrv", "énervé"],
                 ["nspc", "ne surtout pas cliquer"],
                 ["oki", "ok"],
                 ["oseb", "on s'en balance, "],
                 ["osef", "on s'en fou"],
                 ["osefdtl", "on s'en fout de ta vie"],
                 ["osefdtv", "on s'en fout de ta vie"],
                 ["ouer", "oui"],
                 ["ué", "oui"],
                 ["uè", "oui"],
                 ["vi", "oui"],
                 ["mui", "oui"],
                 ["moui", "oui"],
                 ["wé", "oui"],
                 ["woué", "oui"],
                 ["yep", "oui"],
                 ["ouep", "oui"],
                 ["ouè", "oui"],
                 ["oué", "oui"],
                 ["oé", "oui"],
                 ["oè", "oui"],
                 ["ui", "oui"],
                 ["wé", "oui"],
                 ["uep", "oui"],
                 ["vui", "oui"],
                 ["voui", "oui"],
                 ["yup", "oui"],
                 ["wi", "oui"],
                 ["wai", "oui"],
                 ["jtkc", "je t'ai cassé"],
                 ["htkc", "je t'ai cassé"],
                 ["rtl", "raconte ta life"],
                 ["rtva", "racontes ta vie ailleurs"],
                 ["vtfe", "va te faire enculer"],
                 ["tki", "t’es qui"],
                 ["tkl", "tranquille"],
                 ["tllmt", "tellement"],
                 ["tllmnt", "tellement"],
                 ["xd", "explosé de rire"],
                 ["xpldr", "explosé de rire"],
                 ["xdr", "explosé de rire"],
                 ["xpdr", "explosé de rire"],
                 ["taggle", "ta gueule"],
                 ["tg", "ta gueule"],
                 ["tv1", "tu viens"],
                 ["tvb", "tu vas bien"],
                 ["twa", "toi"],
                 ["toa", "toi"],
                 ["toua", "toi"],
                 ["toé", "toi"],
                 ["xlt", "excellent"],
                 ["xl", "excellent"],
                 ["tfk", "tu fais quoi"],
                 ["vtv", "vis ta vie"],
                 ["tpm", "tu n'es pas marrant"],
                 ["snn", "sinon"],
                 ["srx", "sérieux"],
                 ["spj", "sois pas jaloux"],
                 ["tme", "tu m'embêtes"],
                 ["tmlt", "tu me laisses tranquille"],
                 ["tsé", "tu sais"],
                 ["tmk", "tu me manques"],
                 ["slmnt", "seulement"],
                 ["rep", "répond"],
                 ["reuh", "rebonjour"],
                 ["re", "rebonjour"],
                 ["rb", "revient bientôt"],
                 ["rav", "rien à voir"],
                 ["ras", "rien à signaler"],
                 ["raf", "rien à foutre"],
                 ["r10", "j'ai rien dit"],
                 ["ptdr", "pété de rire"],
                 ["ptafqm", "pas tout à fait quand même"],
                 ["pqt", "plus que tout"],
                 ["plv", "pour la vie"],
                 ["pde", "plein d'émotions"],
                 ["liv", "livre"],
                 ["paragr", "paragraphe"],
                 ["sect", "section"],
                 ["bibl", "bibliothèque"],
                 ["cour", "courant"],
                 ["disp", "disponible"],
                 ["élém", "élément"],
                 ["enr", "enregistrée"],
                 ["ét", "étage"],
                 ["exempl", "exemplaire"],
                 ["ff", "frères"],
                 ["form", "format"],
                 ["fs", "faire suite"],
                 ["g", "gauche"],
                 ["gl", "grand livre"],
                 ["b1", "bien"],
                 ["r1", "rien"],
                 ["pro", "professionnel"],
                 ["perso", "personnel"]
                 ]
