patterns = [
    "VERB_ACCOMPLIR OBJ_MA_TACHE ADJ_CONTEXTE",
    "VERB_FINIR toutes mes ADJ_TACHE de ADJ_TRAVAIL et VERB_CELEBRER ADJ_BONNE nouvelle avec ADJ_COPINE",
    "VERB_FONDER ADJ_MAISON avec ADJ_COPINE_2",
    "VERB_TROUVER ADJ-METRIER",
    "ADJ_BONNE_1 ADJ_DOSE de ADJ_MOTIVATION",
    "j'ai ADJ_PEUR des espaces  bonde de monde et de ne NOM_NEGATION VERB_REUSSIR a en sortir si" +
    "je commence ADJ_CRISE de ADJ_PANIQUE",
    "plus de ADJ_CONFIANCE dans le cas ou ADJ_SITUATION VERB_REPRODUIRE",
    "je VERB_VIVRE  ADJ_SEUL et dans la ADJ_PEUR",
    "que je manquais a ADJ_COPINE",
    "ADJ_PASSION de ADJ_COPINE",
    "VERB_ENTOURER par ADJ_COPINE",
    "ADJ_CHOSE ADJ_SIMPLE sont ADJ_MEILLEURES",
    "VERB_RETROUVER ADJ_COPINE apres ADJ_JOUR de ADJ_TRAVAIL",
    "bien VERB_TRAVAILLER et pas VERB_FINIR ADJ_TARD",
    "ADJ_COPINE ADJ_TJR la pour moi",
    "VERB_DEJEUNER avec ADJ_COPINE et VERB_RIGOLER",
    "que je suis ADJ_EXPERT dans mon ADJ_TRAVAIL",
    "VERB_PROFITER ADJ_BEAUCOUP avec ADJ_COPINE",
    "VERB_CONTINUER à VERB_PARTAGETR ADJ_EXPERIENCE et ADJ_JOIE pour que toute les ADJ_PERSONNE qui" +
    "croisent mon chemin VERB_ATTEINT leurs ADJ_BONHEUR",
    "NOM_APPEL avec ADJ_meilleur ADJ_AMIE",
    "que je VERB_POUVOIR VERB_REALISER ADJ_CHOSE ADJ_BIEN",
    "que j'VERB_AIMER etre ADJ_TRANQUILLE pour VERB_TRAVAILLER sans ADJ_CONTRAINTE ADJ_DEPLACEMENT",
    "j'ai ADJ_PEUR de faire des ADJ_ERREURS ADJ_CONTEXTE et ne NOM_NEGATION VERB_EVOLUER",
    "d'VERB_APPRENDRE de mes ADJ_ERREURS pour ne NOM_NEGATION les VERB_REPRODUIRE",
    "CAR je me sentais etre la ADJ_SEUL a vouloir tout VERB_PLANIFIER sans VERB_PASSER a ADJ_ACTION merci",
    "etre VERB_ENTOURER de ADJ_SUPER ADJ_AMI_2 au long de ma vie",
    "me VERB_EVOLUER ADJ_TOUJOURS",
    "a prendre du ADJ_RECUL par rapport avec ADJ_CERTAINES ADJ_PERSONNE",
    "qu'il faut que je me VERB_ORGANISER ADJ_MIEUX et que je suis NOM_NEGATION" +
    "VERB_COMBATTIVE et ADJ_reguliere",
    "ADJ_PEUR de ADJ_CRITIQUE et du ADJ_JUGEMEN surment du a" +
    "VERB_MANQUE de ADJ_CONFIANCE en moi par exemple ADJ_ETE ADJ_DERNIER",
    "le VERB_DEJEUNER du ADJ_TEMPS me a permis de me changer les ADJ_IDEE ADJ_SOIR",
    "les ADJ_MOMENT avec ADJ_COPINE",
    "faire  ADJ_boutique",
    "VERB_REGARDER ADJ_TRUC",
    "VERB_MONTRER plus ADJ_SENTIMENT",
    "VERB_CONTINUER a VERB_DONNER du ADJ_BONHEUR",
    "QUE JE VAIS VERB_REUSSIR mon NOM_PROJET ADJ_CONTEXTE",
    "il VERB_RESTE NOM_CONFIANCE ADJ_EN_LUI",
    "VERB_PARTIR en ADJ_VACANCE",
    "que je ai de moins en moins de ADJ_VOLONTE",
    "VERB_PERTE ma condition physique et peut etre meme ADJ_MORAL",
    "demander a ADJ_COPINE",
    "VERB_PARTIR de chez ADJ_COPINE",
    "VERB_RENCONTRER des ADJ_PERSONNE",
    "VERB_ENTRAINER POUR VERB_DEVENIR NOM_MIEUX",
    "j'ai ADJ_PEUR d'etre ADJ_MAL VERB_JUGER",
    "passer ADJ_JOURNEE ADJ_AGREABLE malgre ADJ_VARICELLE",
    "VERB_REVOIR ADJ_AMIE_2 ADJ_CHER",
    "ADJ_SOIREE avec ADJ_COPINE",
    "ALLER_RETOURE en  NOM_VELO de nuit",
    "VERB_FINIR ADJ_SOIREE sans VERB_PLEURER et ne NOM_NEGATION VERB_AGRESSER ADJ_COPINE",
    "VERBE_PRENDRE_SOIN moi",
    "VERB_FAIRE les petits ADJ_MOT de NOM_NOEL pour les  ADJ_PERSONNE que je VERB_AMIER",
    "VERB_RECEVOIR un ADJ_CADEAU sentimental d'une ADJ_PERSONNE de ADJ_COPINE",
    "elle a su VERB_REBONDIR et VERB_DEVENIR  ADJ_FEMME ADJ_INDP",
    "NOM_APPEL avec ADJ_COPINE",
    "les calins ADJ_SOIR avec ADJ_COPINE",
    "VERB_DEJEUNER  avec ADJ_COPINE",
    "VERB_DEJEUNER",
    "ADJ_SOIREE EN_FAMILLE",
    "VERB_PARTIR ADJ_MARCHE",
    "je VER_COMMENCE a prendre ADJ_GOUT a lire et a VERB_APPROFONDIR et"
    + "de VERB_PARLER mais surtout VERB_ECOUTER plus",
    "me VERB_LIBERER de ADJ_COLERE et VERB_TRAVAILLER pour moi",
    "Je peux passer ADJ_BELLE ADJ_Belle_JOURNEE EN_TRAVAILLANT sur ce qui VERB_INTERESSER",
    "ADJ_MESSAGE que je me suis offert",
    "VERB_REPRENDRE MES_COURS et me faire du bien",
    "je VERB_POUVOIR_1 m’ouvrir à plus d'amour et etre ADJ_BONNE personne",
    "ADJ_COUR NOM_KUNDALINI_YOGA",
    "VERB_FINIR de ADJ_OFFRE dans le cadre de mon NOM_PROJET ADJ_CONTEXTE",
    "je VERB_POUVOIR VERB_REALISER ADJ_PLEIN ADj_PLEIN_CHOSE ADJ_DIVERSIFIEES dans la meme ADJ_Belle_JOURNEE",
    "ADJ_CONFERENCE sur ADJ_STRESS et neurosciences",
    "VERB_EVOLUER sur mon NOM_PROJET et sur le ADJ_TRAVAIL sur moi",
    "que je VERB_POUVOIR VERB_REALISER ADJ_PLEIN de ADj_PLEIN_CHOSE" +
    "ADJ_DIVERSIFIEES dans une ADJ_Belle_JOURNEE",
    "VERB_RANGER",
    "etre ADJ_HEUREUX",
    "que mon ADJ_TRAVAIL n'etait NOM_NEGATION fait pour moi",
    "ADJ_BALADE dans ADJ_NATURE",
    "VERB_SENTIR ADJ_MIEUX_1",
    "ADJ_COPINE me font confiance",
    "ADJ_REPA ADJ_CREPE",
    "la VERB_PERTE de ADJ_JOIE de vivre",
    "le ADJ_DEGOUT",
    "la ADJ_DEPRIME",
    "VERB_SE_CONNAITRE encore mieux",
    "VERB_POSTULER dans ADJ_LABO",
    "m'VERB_INVESTIR dans un vrai NOM_PROJET",
    "la ADJ_PEUR de VERB_QUITTER mon ADJ_TRAVAIL et de VERB_GALERER ensuite TOUT_MA_VIE",
    "que ADJ_LIBERTE m'est ADJ_ESSENTIELLE",
    "NOM_APPEL avec ADJ_COPINE Sandrine",
    "VERB_PROFITER des ADJ_PERSONNE que j'VERB_AIMER",
    "instalation ADJ_FIBRE",
    "j'ai ete ADJ_SUPER_1 et de ADJ_BONNE_1 toute ADJ_SOIREE",
    "NOM_JEUX avec ADJ_COPINE",
    "VERB_LIMITER l'NOM_UTILISATION des RESEAUX_SOCIAUX",
    "Je me sens ADJ_BEAUCOUP_1 ADJ_MIEUX_2 quand je VERB_FAIRE_1 un ADJ_PEU d'ADJ_EXERCICE",
    "avoir pu VERB_REGARDER NOM_FILM dont j'avais envie",
    "VERB_AMUSER des ADJ_ENFANTS",
    "rien est acquis",
    "NOM_ANNIVERSAIRE",
    "RENDRE_SERVICE POUR VERB_LIVRER de NOM_MARCHANDISE ADJ_DELECIEUSE",
    "ADJ_BELLE ADJ_SEANCE aux pistoliers d'Auteuil",
    "METTRE_DE_ORDRE dans NOM_DOCUMENTS ADJ_CONTEXTE",
    "Rien n'est Jamais acquis",
    "ADJ_SOIREE",
    "VERB_LIRE NOM_HISTOIRE par PAR_JOUR ou NOM_JEUX avec ADJ_COPINE",
    "VERB_UTILISER le moins possible de plastique emporter des bocaux au magasin",
    "ADJ_COUR MAARS",
    "ADJ_MOMONET_1 EN_FAMILLE Vive ADJ_SAMEDI",
    "ADJ_BALADE et decouverte de NOM_REGION",
    "on est ADJ_SOULAGER lors que ADJ_CERTAINES ADJ_TACHE " +
    "administratives VERB_REALISER meme si non ADJ_INTERESSANTE",
    "Etre ADJ_HEUREUX EN_FAMILLE et passer ADJ_BEAUX ADJ_MOMENT_2 ADJ_MOMENT_2",
    "VERB_FINIR mes ADJ_TACHE",
    "Manger des ADJ_FRUITS",
    "Connaissance du Textile et reconnu dans le ADJ_TRAVAIL",
    "droit",
    "passer du ADJ_BON temps EN_FAMILLE et ADJ_DEHORS avec ADJ_NEIGE",
    "a VERB_RIGOLER sans s VERB_ARRETER",
    "ADJ_Belle_JOURNEE Click and COllect bon ADJ_RESTAURANT",
    "faire NOM_FORMATION en ADJ_BUSNESS / compta",
    "Me mettre a mon compte en tant que Support technique/formateur",
    "etre sur de trouver un ADJ_TRAVAIL qui me VERB_PALIRE",
    "VERB_DONNER un ADJ_COUR_1 a des NOM_ETUDIANT via RESEAUX_SOCIAUX",
    "Frederic Helfrich",
    "ADJ_COURAGEUSE et fonçeuse",
    "ADJ_COPINE",
    "Donner la rythmique de ADJ_SOIREE",
    "NEGATION_PLUS VERB_SUIVRE ADJ_COPINE",
    "VERB_DECORER le NOM_SAPIN",
    "VERB_PARTAGETR le ADJ_MOMENT cuisine",
    "perte du ADJ_TRAVAIL",
    "un NOM_PROJET ADJ_RATE"
]
