replacements = [
    [r"\n", ""],
    [r".\\n", ". "],
    [r"\\n", ". "],
    [r"n'", " ne "],
    [r"n’", " ne "],
    [r"d’", " de "],
    [r"d'", " de "],
    [r"j'", " je "],
    [r"j’", " je "],
    [r"m'", " me "],
    [r"m’", " me "],
    [r"l'", " le "],
    [r"l’", " le "],
    [r"t’", " te "],
    [r"t'", " te "],
    [r"s’", " se "],
    [r"s'", " se "],
    [r"c’", " ce "],
    [r"c'", " ce "]
]